export const CONNECT_WALLET = "CONNECT_WALLET";
export const PROFILE_REQUEST = "PROFILE_REQUEST";
export const PROFILE_SUCCESS = "PROFILE_SUCCESS";
export const PROFILE_FAIL = "PROFILE_FAIL";

// Market place
export const GET_ALL_NFTS_REQUEST = "GET_ALL_NFTS_REQUEST";
export const GET_ALL_NFTS_SUCCESS = "GET_ALL_NFTS_SUCCESS";
export const GET_ALL_NFTS_FAIL = "GET_ALL_NFTS_FAIL";
export const GET_TYPE_OF_NFT = "GET_TYPE_OF_NFT";
export const GET_COUNTDOWN = "GET_COUNTDOWN";

export const GET_NETWORK_ID = "GET_NETWORK_ID";
export const GET_ASSET_DATA = "GET_ASSET_DATA";
